futsal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',RedirectView.as_view(url='futsal/')),
    path('accounts/', include('accounts.urls')),
    path('futsal/',include('futsalApp.urls')),
    path('booking/',include('booking.urls')),
    path('team/',include('team.urls')),
    path('match/',include('match.urls')),
    ############# API ENDPOINTS #############
    path('api/auth/',include('accounts.api.urls')),
    path('api/booking/',include('booking.api.urls')),
    path('api/futsal/',include('futsalApp.api.urls')),
    path('api/team/',include('team.api.urls')),
    path('api/match/',include('match.api.urls')),
    ############ Social Authentication #########    
    path('oauth/',include('social_django.urls',namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team/api/urls.py
from django.urls import path
from .views import TeamListAPI, TeamDetailAPI, TeamMemberListAPI, TeamMemberDetailAPI

urlpatterns = [
    path('',TeamListAPI.as_view(),name='team'),
    path('<int:pk>/',TeamDetailAPI.as_view(),name='team-detail'),
    path('members/',TeamMemberListAPI.as_view(),name='team-members'),
    path('members/<int:pk>/',TeamMemberDetailAPI.as_view(),name='team-member-detail')
]

team/urls.py
from django.urls import path
from .views import (TeamCreateView,
TeamDetailView,
TeamUpdateView,
JoinTeamView,
LeaveTeamView,
TeamDeleteView,
RemoveMemberView,
TeamIndexView,
TeamSearchView)

urlpatterns = [
    path('',TeamIndexView.as_view(),name='team-index'),
    path('create/',TeamCreateView.as_view(),name='team-create'),
    path('search',TeamSearchView.as_view(),name='team-search'),
    path('<slug:slug>',TeamDetailView.as_view(),name='team-detail'),
    path('update/<slug:slug>',TeamUpdateView.as_view(),name='team-update'),
    path('delete/<int:pk>/<slug:slug>',TeamDeleteView.as_view(),name='team-delete'),
    path('join/<slug:slug>/',JoinTeamView.as_view(),name='join-team'),
    path('leave/<slug:slug>/',LeaveTeamView.as_view(),name='leave-team'),
    path('remove/<slug:slug>/',RemoveMemberView.as_view(),name='remove-member'),
]

team/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse
from django.utils.text import slugify
from futsalApp.models import Futsal
from django.db.models.signals import pre_save
# Create your models here.
class Team(models.Model):
    name   = models.CharField(max_length=100)
    admin  = models.ForeignKey(User, related_name='admin',on_delete=models.DO_NOTHING)
    logo   = models.ImageField(upload_to='Team', default='default.png')
    bio    = models.TextField()
    members = models.ManyToManyField(User, through='TeamMember')
    slug    = models.SlugField(unique=True,blank=True,null=True,max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Team.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        return super().save(*args,**kwargs)
    
    def get_absolute_url(self):
        return reverse('team-detail', kwargs={'slug':self.slug})

class TeamMember(models.Model):
    team = models.ForeignKey(Team, related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ('team', 'user')


def capitalize_name(sender, instance, *args, **kwargs):
    instance.name = instance.name.title()

pre_save.connect(capitalize_name, sender=Team)

team/forms.py
from django import forms
from .models import Team

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'bio', 'logo', 'slug']
        exclude = ('slug',)
         
    

team/api/views.py
from .serializers import TeamSerializer, TeamMemberSerializer
from team.models import Team, TeamMember
from rest_framework import generics, mixins, permissions, authentication

class TeamListAPI(generics.ListAPIView, mixins.CreateModelMixin):
    serializer_class = TeamSerializer

    def get_queryset(self):
        qs = Team.objects.all()
        return qs
    
    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)
    
    def perform_create(self, serializer):
        return serializer.save(admin=self.request.user)

class TeamDetailAPI(generics.RetrieveAPIView, mixins.UpdateModelMixin, mixins.DestroyModelMixin):
    serializer_class = TeamSerializer
    queryset         = Team.objects.all()

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)
    
    def patch(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)
    
    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

class TeamMemberListAPI(generics.ListAPIView, mixins.CreateModelMixin):
    serializer_class = TeamMemberSerializer
    def get_queryset(self):
        qs = TeamMember.objects.all()
        return qs

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)
    
    def perform_create(self, serializer):
        return serializer.save(user=self.request.user)

class TeamMemberDetailAPI(generics.RetrieveAPIView, mixins.UpdateModelMixin, mixins.DestroyModelMixin):
    serializer_class = TeamMemberSerializer
    queryset         = TeamMember.objects.all()

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)
    
    def patch(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)
    
    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

team/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from .forms import TeamForm
from .models import Team, TeamMember
from match.models import Match,MatchObject
from django.views import generic
from django.contrib import messages
from django.db.models import Q

class TeamIndexView(LoginRequiredMixin, generic.ListView):
    model = Team
    template_name = 'team/index.html'
    context_object_name = 'teams'

    def get_queryset(self):
        queryset = Team.objects.all().exclude(members__id=self.request.user.id).order_by('?')[:4]
        return queryset

    def get_team(self):
        try:
            member = TeamMember.objects.get(user=self.request.user)
            return member.team
        except:
            member = None
        return None

    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['user_team'] = self.get_team()
        return context
    

class TeamCreateView(LoginRequiredMixin, generic.CreateView):
    model = Team
    template_name = 'team/create.html'
    form_class = TeamForm

    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['title'] = 'Create Team'
        return context
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.admin = self.request.user
        instance.save()
        instance.members.add(self.request.user)
        messages.success(self.request, 'Team created successfully.')
        return redirect(instance.get_absolute_url())

class TeamDetailView(LoginRequiredMixin, generic.DetailView):
    model = Team
    template_name = 'team/team.html'
    context_object_name = 'team'
    slug_url_kwarg = 'slug'

    def get_team(self):
        team = get_object_or_404(Team, slug=self.kwargs.get('slug'))
        return team

    def get_match_requests(self):
        try:
            match_requests = Match.objects.filter(matchobject__opponent=None)
        except:
            match_requests = None
        return match_requests
    
    def get_matches(self):
        try:
            matches = MatchObject.objects.filter(
            Q(match = self.get_match_requests()[:1]) |
            Q(opponent = self.get_team())
            )
        except:
            matches = None
        return matches

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['match_requests'] = self.get_match_requests()
        context['matches'] = self.get_matches()
        return context
    
class TeamUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Team
    template_name = 'team/edit.html'
    form_class    = TeamForm

    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['title'] = 'Edit Team'
        return context

    def get_queryset(self):
        return Team.objects.filter(admin=self.request.user)
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.admin = self.request.user
        instance.slug  = instance._get_unique_slug()
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())

class TeamDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Team
    template_name = 'team/delete.html'
    success_url = reverse_lazy('home')
    context_object_name = 'team'
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Team deleted successfully.')
        return super().delete(self,request, *args, **kwargs)

class JoinTeamView(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('team-detail',kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self, request, *args, **kwargs):
        team   = get_object_or_404(Team, slug=self.kwargs.get('slug'))
        already_member = TeamMember.objects.filter(user=self.request.user).exists()
        if already_member:
            messages.warning(self.request, 'Already in another team.')
            return HttpResponseRedirect(self.get_redirect_url())
        try:
            TeamMember.objects.create(user=self.request.user,team=team)
        except:
            messages.warning(self.request, 'Already in team.')
        else:
            messages.success(self.request, 'You are now a member.')
        
        return super().get(request, *args, **kwargs)


class LeaveTeamView(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('team-detail', kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self, request, *args, **kwargs):
        try:
            membership = TeamMember.objects.filter(
            user = self.request.user,
            team__slug = self.kwargs.get('slug')
        ).get()
        except TeamMember.DoesNotExists:
            messages.warning(self.request, 'Sorry you are not in the team.')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the team.')

        return super().get(request, *args, **kwargs)

class RemoveMemberView(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('team-detail', kwargs={'slug':self.kwargs.get('slug')})

    def post(self, request, *args, **kwargs):
        try:
            member = TeamMember.objects.get(user__id = self.request.POST.get('member_id'))
        except:
            messages.warning(self.request, 'Error')
        else:
            member.delete()
            messages.success(self.request, 'Removed')
        return self.get(request, *args, **kwargs)

class TeamSearchView(LoginRequiredMixin, generic.ListView):
    model = Team
    template_name = 'team/search.html'
    context_object_name = 'teams'

    def get_queryset(self):
        search_query = []
        search_term = self.request.GET.get('q')
        if search_term is not None:
            search_query = Team.objects.filter(
                Q(name__icontains = search_term)
            )
        return search_query
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['teams'] = self.get_queryset()
        context['search_term'] = self.request.GET.get('q')
        return context

templates/team/create.html
{% extends 'base.html' %}
{% block title %} Create Team {% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card mt-3">
                <div class="card-header py-1">
<h3 class="text-center" style="font-family:'Nunito';color:#6912A7"> {{title}}  </h3>
                </div>
                <div class="card-body">
                    <form action="" enctype="multipart/form-data" method="POST">
                        {% csrf_token %}
                    {{form}}
                    <small class="text-center">  </small>
                <button type="submit" class="mt-2"> {{title}} </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<style>
        button {
            display: inline-block;
            font-weight: 400;
            color: snow;
            text-align: center;
            vertical-align: middle;
            cursor: pointer;
            user-select: none;
            background-color: #3ac57f;
            border: 1px solid transparent;
            padding: .375rem .75rem;
            font-size: 1rem;
            line-height: 1.5;
            border-radius: .25rem;
        }
        button:hover {
            background: #2ea569;
        }

        label {
            color: #666666;
            font-family: 'Nunito';
            font-weight: 500;
            margin:3px 0;
        }
        #id_name{
            width: 99%;
            border: none;
            border-bottom: 3px #6912A7 solid;
            height: 20px;
            margin: -20px 0 0 5px;
            outline: none;
           
        }
        #id_bio{
            width: 100%;
            border: none;
            border: 2px #666666 solid;
            height: 100px;
            outline: none;
           
        }
        input[type="file"] {
            display: none;
        }
        label[for="id_logo"] {
            border: 2px solid #6912A7;
            display:block;
            margin: 10px 0 0 0;
            height:30px;
            padding: 3px 0;
            width: 60px;
            cursor: pointer;
        }
        label[for="id_logo"]:hover {
            border: 2px solid #3ac57f;
            background: #3ac57f;
            color: white;
            transition: .3s;
        }
        #id_name:focus{
            border-bottom: 3px #3ac57f solid;
            transition: .3s;
        }
        #id_bio:focus{
            border: 3px #3ac57f solid;
            transition: .3s;
        }
        small{
            display: none;
        }
        .show {
            display: block;
            color: #6912A7;
            font-weight: 600;
        }
</style>

<script>
        document.querySelector('#id_logo').onchange = function () {
            var text = document.querySelector('small');
            text.innerHTML = 'selected image: ' + this.value;
            text.classList.add('show');
            };
    </script>

{% endblock content %}

templates/team/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
 
{% endblock title %}

{% block content %}

<div class="container card w-25 p-4 mt-4 mb-3">
    <form action="" method="POST" enctype="multipart/form-data">
        <p> Confirm delete team? </p>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Delete" class="w-100 text-center my-2 btn btn-danger text-white">
    </form>
</div>



{% endblock content %}

templates/team/edit.html
{% extends 'base.html' %}
{% block title %} Create Team {% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card mt-3">
                <div class="card-header py-1">
<h3 class="text-center" style="font-family:'Nunito';color:#6912A7"> {{title}}  </h3>
                </div>
                <div class="card-body">
                    <form action="" enctype="multipart/form-data" method="POST">
                        {% csrf_token %}
                    {{form}}
                    <small class="text-center">  </small>
                <button type="submit" class="mt-2"> {{title}} </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<style>
        button {
            display: inline-block;
            font-weight: 400;
            color: snow;
            text-align: center;
            vertical-align: middle;
            cursor: pointer;
            user-select: none;
            background-color: #3ac57f;
            border: 1px solid transparent;
            padding: .375rem .75rem;
            font-size: 1rem;
            line-height: 1.5;
            border-radius: .25rem;
        }
        button:hover {
            background: #2ea569;
        }

        label {
            color: #666666;
            font-family: 'Nunito';
            font-weight: 500;
            margin:3px 0;
        }
        #id_name{
            width: 99%;
            border: none;
            border-bottom: 3px #6912A7 solid;
            height: 20px;
            margin: -20px 0 0 5px;
            outline: none;
           
        }
        #id_bio{
            width: 100%;
            border: none;
            border: 2px #666666 solid;
            height: 100px;
            outline: none;
           
        }
        input[type="file"] {
            display: none;
        }
        label[for="id_logo"] {
            border: 2px solid #6912A7;
            display:block;
            margin: 10px 0 0 0;
            height:30px;
            padding: 3px 0;
            width: 60px;
            cursor: pointer;
        }
        label[for="id_logo"]:hover {
            border: 2px solid #3ac57f;
            background: #3ac57f;
            color: white;
            transition: .3s;
        }
        #id_name:focus{
            border-bottom: 3px #3ac57f solid;
            transition: .3s;
        }
        #id_bio:focus{
            border: 3px #3ac57f solid;
            transition: .3s;
        }
        small{
            display: none;
        }
        .show {
            display: block;
            color: #6912A7;
            font-weight: 600;
        }
</style>

<script>
        document.querySelector('#id_logo').onchange = function () {
            var text = document.querySelector('small');
            text.innerHTML = 'selected image: ' + this.value;
            text.classList.add('show');
            };
    </script>

{% endblock content %}

templates/team/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Futboot Team {% endblock title %}

{% block content %}
<!--About heading-->
<div class="container pb-0" id="sec1">
    <div class="row">
        <div class="col-lg-5 mt-2">
            <!-- search form -->
            <form action="{% url 'team-search' %}" method="get">
                <input type="search" name="q" id="" placeholder="search teams..">
                <input type="submit" value="search">
            </form>
            <img src="{% static 'images/goal.png' %}" alt="img1" class="img-fluid w-100" height="400">
        </div>
        <div class="col-lg-6 ml-2">
            <h3 class="text-center text-bold"> Futboot Team </h3>
            <div class="mx-auto" id="menu">
            <div class="menu-item">
                <p><a href="{% url 'team-create' %}"> Create Team  </a></p> 
            </div>

            <div class="menu-item">
                <p> Join Team  </p>
            </div>
                
            <div class="menu-item">
                <p><a href="{% url 'match-index' %}"> Play Match  </a></p> 
                </div>
            </div>
            <!-- user team -->
            {% if user_team %}
            <div class="card mx-auto p-1">
                <div class="card-body">
                    <div class="row m-0 d-flex justify-content-center mb-2">
                            <img src="{{user_team.logo.url}}" alt="" height="70" width="70" style="border-radius: 50%;" class="my-auto">
                            <div class="card-title mt-2">
                                    <h4 class="text-center mt-2"> {{user_team.name}} </h4>
                                </div>
                        <div class="container mt-2">
                                <div class="row">
                                        <div class="col-md-4 col-sm-4">
                                                <a href="{{user_team.get_absolute_url}}">
                                                    <button id="visit">visit</button>
                                                </a>
                                            </div>
                    
                                            <div class="col-md-4 col-sm-4">
                                                <p> {{user_team.members.all.count}} Members</p>
                                            </div>
                    
                                </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    <hr>
</div>

<div class="container" id="sec1">
    <h3> Join Team </h3>
    <div class="row">
        <div class="col-md-5">
            {% for team in teams %}
            {% include 'partials/team/team.html' %}
            {% endfor %}
        </div>
        <div class="col-md-5 ml-auto">
            <img src="{% static 'images/player.png' %}" alt="" class=" img-fluid w-100 h-100">
        </div>
    </div>
</div>

<!--footer-->
<!-- <footer class="container-fluid text-center bg-dark text-light mt-4 py-3">
    <h3 class="lead d-inline">FIFA WORLD CUP </h3> &copy;
</footer> -->


<style>
    body {
        background: #ffffff;
    }
    a {text-decoration: none;}
    #sec1 {
        background: #ffffff !important;
    }

    form {
        display: flex;
        align-items: center;
        justify-content: start;
    }

    input {
        border: 1px ridge rgb(219, 218, 218);
        height: 29px;
        margin: 0;
    }

    input[type="search"] {
        border-right: none;
        border-bottom: none;
    }

    input[type="submit"] {
        cursor: pointer;
        color: #F5F5F5;
        border-top-right-radius: 12px;
        border-bottom-right-radius: 12px;
        background: #3ac57f;
    }

    input[type="submit"]:hover {
        background: #33a56c;
    }

    h3 {
        font-weight: 600;
        color: #7C33AA;
    }

    h4,
    p {
        color: #7C33AA;
    }

    #menu {
        display: flex;
        justify-content: space-evenly;
        align-items: center;
    }
    .menu-item {
        height: 40px;
        color: #33a56c;
        padding: 5px;
        text-decoration: none;
        margin: 10px;
        border: 3px solid #3ac57f;
    }
    .menu-item p a {
        text-decoration: none;
        color: #33a56c;
        font-size: 18px;
        font-weight: 500;
    }
    .menu-item p {
        color: #33a56c;
        font-size: 18px;
        font-weight: 500;
    }
    .menu-item:hover , .menu-item p a:hover, .menu-item p:hover{
        background: #33a56c;
        color: #F5F5F5;
        transition: .5s;
        cursor: pointer;
    }

    ul {
        display: flex;
        flex-direction: row;
        align-items: flex-start;
        justify-content: space-between;
    }

    li {
        list-style: none;
    }

    #visit {
        background: #3ac57f;
        width: 70px;
        border: 2px #3ac57f;
        color: white;
    }

    #visit:hover {
        background: #33a56c;
        transition: .2s;
    }

    @media screen and (max-width:678px) {
        .img-fluid { display: none; }
        .menu-item p a, .menu-item p { font-size: 15px; }
        
    }
</style>
{% endblock content %}

templates/team/search.html
{% extends 'base.html' %}

{% block title %} {{search_term}} {% endblock title %}

{% block content %}

<div class="container mt-2">
    <h4 class="text-left" style="color: #2f9c66;">Results for {{search_term}} </h4>
    <!-- search form -->
    <form action="" method="get">
            <input type="search" name="q" id="" placeholder="search teams..">
            <button type="submit" id="search-btn"> <i class="fas fa-search"></i> </button>
        </form>
        </div>
<hr>

<div class="container">
<div class="row">
        <div class="col-md-5">
            {% for team in teams %}
            <div class="card my-2" id="item">
                    <div class="img">
                        <img class="" src="{{team.logo.url}}" alt="Card image cap" height="60" width="60" style="border-radius:50%">
                    </div>
                    <div class="name">
                    <span class="text-center" id="teamname"> 
                        <a href="{{team.get_absolute_url}} "> {{team.name}}  </a>
                    </span>
                    </div>
                        <div class="col-md-4"> <span> {{team.members.all.count}} members </span> </div>
                    
                        <div>
                            <a href="{% url 'join-team' slug=team.slug %}">
                                <button id="visit"> Join </button>
                            </a>
                        </div>
            </div>
            
            {% endfor %}
        </div>
    </div>
</div>

<style>
        #item {
            display: flex;
            flex-direction: row;
            align-items: center;
            justify-content: space-around;
        }
        #teamname a {
            background: none;
            border: none;
            color: #7C33AA;
            font-size: 1.1rem;
        }
        #visit {
            background: #3ac57f;
            width: 70px;
            border: 2px #3ac57f;
            color: white;
        }
    
        #visit:hover {
            background: #33a56c;
            transition: .2s;
        }
        form {
            display: flex;
            align-items: flex-start;
            justify-content: start;
        }
    
        input {
            border: 1px ridge rgb(219, 218, 218);
            height: 29px;
            margin: 0;
        }
        #search-btn {
            border: none;
            height: 29px;
            background: #33a56c;
            color: white;
        }
    
        input[type="submit"] {
            cursor: pointer;
            color: #F5F5F5;
            font-size: 13px;
            width: 50px;
            border: none !important;
            background: #3ac57f;
        }
    
        input[type="submit"]:hover {
            background: #33a56c;
        }
    </style>

{% endblock content %}