accounts/api/urls.py
from django.urls import path
from .views import RegisterAPIView,ProfileAPIView, ProfileRetriveAPI,LoginView,LogoutView

urlpatterns = [
    path('register/',RegisterAPIView.as_view(),name='register'),
    path('profile/',ProfileAPIView.as_view(),name='user-list-api'),
    path('profile/<int:pk>/',ProfileRetriveAPI.as_view(),name='user-api'),
    path('login/',LoginView.as_view(),name='api-login'),
    path('logout/',LogoutView.as_view(),name='api-logout'),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (RegisterView, UpdateProfileView, ChangePasswordView,AddToFavourite,UserDashboardView)

urlpatterns = [
    path('signup/',RegisterView,name='signup'),
    path('profile/',UpdateProfileView,name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name="accounts/logout.html"),name='logout'),
    path('change-password/',ChangePasswordView,name='change-password'),
    path('save/',AddToFavourite,name='save'),
    path('dashboard/',UserDashboardView.as_view(),name='dashboard'),
]

futsal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',RedirectView.as_view(url='futsal/')),
    path('accounts/', include('accounts.urls')),
    path('futsal/',include('futsalApp.urls')),
    path('booking/',include('booking.urls')),
    path('team/',include('team.urls')),
    path('match/',include('match.urls')),
    ############# API ENDPOINTS #############
    path('api/auth/',include('accounts.api.urls')),
    path('api/booking/',include('booking.api.urls')),
    path('api/futsal/',include('futsalApp.api.urls')),
    path('api/team/',include('team.api.urls')),
    path('api/match/',include('match.api.urls')),
    ############ Social Authentication #########    
    path('oauth/',include('social_django.urls',namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team/urls.py
from django.urls import path
from .views import (TeamCreateView,
TeamDetailView,
TeamUpdateView,
JoinTeamView,
LeaveTeamView,
TeamDeleteView,
RemoveMemberView,
TeamIndexView,
TeamSearchView)

urlpatterns = [
    path('',TeamIndexView.as_view(),name='team-index'),
    path('create/',TeamCreateView.as_view(),name='team-create'),
    path('search',TeamSearchView.as_view(),name='team-search'),
    path('<slug:slug>',TeamDetailView.as_view(),name='team-detail'),
    path('update/<slug:slug>',TeamUpdateView.as_view(),name='team-update'),
    path('delete/<int:pk>/<slug:slug>',TeamDeleteView.as_view(),name='team-delete'),
    path('join/<slug:slug>/',JoinTeamView.as_view(),name='join-team'),
    path('leave/<slug:slug>/',LeaveTeamView.as_view(),name='leave-team'),
    path('remove/<slug:slug>/',RemoveMemberView.as_view(),name='remove-member'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save
from PIL import Image
from futsalApp.models import Futsal
# Create your models here.

class Profile(models.Model):
    user       = models.OneToOneField(User,on_delete=models.CASCADE)
    avatar     = models.ImageField(default='default.png', upload_to='Profile')
    favourites = models.ManyToManyField(Futsal,blank=True,null=True)
    is_owner   = models.BooleanField(default=False)

    def __str__(self):
        return 'Profile of {}'.format(self.user.username)
    
    # def get_absolute_url(self):
    #     return reverse('profile', kwargs={'username':self.user.username})

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.avatar.path)
        if img.height > 300 or img.width > 300:
            outputSize = (300,300)
            img.thumbnail(outputSize)
            img.save(self.avatar.path)
    
def profile_create(sender, instance, created ,*args, **kwargs):
    if created:
        Profile.objects.create(user = instance)

def profile_save(instance, *args, **kwargs):
    instance.profile.save()

post_save.connect(profile_create, sender=User)
post_save.connect(profile_save, sender=User)

    

    

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models  import Profile

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(label='email')

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def validate_email(self):
        email = self.cleaned_data.get('email')
        user  = User.objects.filter(email = email).exists()
        if user:
            raise forms.ValidationError('email already taken.')
        return email

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(label='email')

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        
        for fieldname in ['username', 'email']:
            self.fields[fieldname].help_text = None

    class Meta:
        model  = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ['avatar',]

accounts/api/views.py
from rest_framework import generics, parsers, mixins
from rest_framework.views import APIView
from rest_framework import permissions, authentication
from django.contrib.auth.models import User
from accounts.models import Profile
from .serializers import UserRegisterSerializer, ProfileSerializer, LoginSerializer
from django.contrib.auth import login, logout
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from rest_framework.authentication import TokenAuthentication

class RegisterAPIView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserRegisterSerializer
    permission_classes = [permissions.AllowAny]
    parser_classes = [parsers.MultiPartParser,parsers.FormParser,parsers.JSONParser]

class ProfileAPIView(generics.ListAPIView,mixins.CreateModelMixin):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer
    permission_classes = [permissions.AllowAny]

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)
    
    def perform_create(self, serializer):
        return serializer.save(user=request.user)

class ProfileRetriveAPI(generics.RetrieveAPIView,mixins.UpdateModelMixin):
    serializer_class = ProfileSerializer
    queryset         = Profile.objects.all()

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)
    
    def patch(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

class LoginView(APIView):
    def post(self, request, *args, **kwargs):
        serializer = LoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user  = serializer.validated_data['user']
        login(request, user)
        token, created = Token.objects.get_or_create(user=user)
        return Response({'token':token.key}, status=200)

class LogoutView(APIView):
    authentication_classes = [TokenAuthentication]
    def post(self, request):
        logout(request)
        return Response({'message':'Logged Out'}, status=200)
        

accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponseRedirect
from .forms import UserRegistrationForm,UserUpdateForm,ProfileUpdateForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.signals import user_logged_in
from django.contrib.auth.decorators import login_required
from booking.models import Booking
from futsalApp.models import Futsal
from django.views import generic
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

def RegisterView(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Welcome {}'.format(username))
            return redirect('login')
    else:
        form = UserRegistrationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/signup.html', context)

def logged_in_message(sender, user, request, **kwargs):
    user = request.user
    messages.info(request, 'Welcome {}'.format(user.username))
user_logged_in.connect(logged_in_message)

# update page of the user 
@login_required
def UpdateProfileView(request):
    user = request.user
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=user)
        p_form = ProfileUpdateForm(request.POST or None,request.FILES or None,instance = user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Profile Updated')
            redirect('profile')
    else:
        u_form = UserUpdateForm(instance=user)
        p_form = ProfileUpdateForm(instance=user.profile)

    context = {
        'u_form':u_form,
        'p_form':p_form,
        'user':user,
    }
    return render(request, 'accounts/profile.html',context)
        
@login_required
def ChangePasswordView(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password is successfully changed.')
            return redirect('change-password')
        else:
            messages.error(request, 'Please enter correctly.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/password.html', {'form':form})


def AddToFavourite(request):
    print('liked')
    context = {}
    user = request.user
    futsal = get_object_or_404(Futsal, id=request.POST.get('futsal_id',None))
    print(futsal)
    is_saved = False
    if request.method == "POST":
        if user.profile.favourites.filter(id=futsal.id).exists():
            user.profile.favourites.remove(futsal)
            is_saved = False
        else:
            user.profile.favourites.add(futsal)
            is_saved = True
    context = {
        'is_saved':is_saved,
    }
    return JsonResponse({'data':context})


class UserDashboardView(LoginRequiredMixin, generic.ListView):
    model = Booking
    template_name = 'accounts/dashboard.html'
    context_object_name = 'bookings'

    def get_queryset(self):
        return Booking.objects.filter(user=self.request.user)

    def get_saved_futsals(self):
        user = self.request.user
        futsals = user.profile.favourites.all()
        return futsals

    

    def get_context_data(self, *args, **kwargs):
        booking = self.get_queryset()
        context = super().get_context_data(*args, **kwargs)
        context['queryset'] = booking
        context['today_booking'] = booking.filter(date=datetime.datetime.today())
        context['saved'] = self.get_saved_futsals()
        return context

templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block title %} Dashboard {% endblock title %}

{% block content %}

<div class="container">
    <h2 class="font-weight:800;"> Dashboard  </h2>
</div>

<div class="container ">
    <div class="alert alert-secondary text-dark py-2" role="alert">
        <a href="{% url 'dashboard' %}">Dashboard</a> / <a href="{% url 'home' %}">Home</a> / <a href="{% url 'booking' %}">Book Futsal</a>
    </div>
</div>


<div class="container">
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab"
                aria-controls="nav-home" aria-selected="true">Today' Booking</a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab"
                aria-controls="nav-profile" aria-selected="false">Valid Booking</a>
            <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab"
                aria-controls="nav-contact" aria-selected="false">Saved Futsals</a>
        </div>
    </nav>
</div>

<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
        <div class="container">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Futsal</th>
                        <th scope="col">Date</th>
                        <th scope="col">Time</th>
                    </tr>
                </thead>
                <tbody class="zz">
                    {% for booking in today_booking %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>
                            <img src="{{booking.futsal.main_img.url}}" alt="" height="30" width="30"
                                style="border-radius:50%;">
                        <a href="{{booking.futsal.get_absolute_url}}"> {{booking.futsal}} </a>
                        </td>
                        <td>{{booking.date}}</td>
                        <td>{{booking.time}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>
</div>


<div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">

    <div class="container">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Futsal Name</th>
                    <th scope="col">Date</th>
                    <th scope="col">Time</th>
                </tr>
            </thead>
            <tbody class="zz">
                {% for booking in queryset %}
                {% if booking.is_valid %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>
                        <img src="{{booking.futsal.main_img.url}}" alt="" height="30" width="30"
                            style="border-radius:50%;"> 
                            <a href="{{booking.futsal.get_absolute_url}}"> {{booking.futsal}} </a>
                    </td>
                    <td>{{booking.date}}</td>
                    <td>{{booking.time}}</td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>


<div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
    <div class="container">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Futsal Name</th>
                    <th scope="col">Location</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody class="zz">
                {% for futsal in saved %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>
                        <img src="{{futsal.main_img.url}}" alt="" height="40" width="40"
                            style="border-radius:50%;">
                             <a href="{{futsal.get_absolute_url}}">
                                {{futsal.name}}
                            </a>
                    </td>
                    <td>{{futsal.location}}</td>
                    <td>{{futsal.price}} /hr</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
</div>

<style>
    td {
        font-family: 'Nunito';
        font-weight: 600;
    }
    a {
       
        text-decoration: none;
        cursor: pointer;
    }
    a:hover {
        text-decoration: none;
        color: #3ac57f;
    }
</style>
{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Sign Up {% endblock title %}

{% block content %}

{% include 'partials/_message.html' %}

<div class="container py-2 mt-2 mb-3">
    <div class="row">
        <div class="col-md-6 mx-auto card">
            <form action="" method="POST" enctype="multipart/form-data" class="">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Login to Futbook </legend>
                    <div class="row">
                        <div class="col-md-7">
                            {{ form }}
                            <div class="form-group">
                                    <button class="" type="submit">Login</button>
                                </div>
                        </div>
                        <div class="col-md-5 my-auto">
            <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-danger btn-block">
                Google <i class="fa fa-google-plus"></i>
            </a>
            <a href="{% url 'social:begin' 'github' %}" class="btn btn-secondary btn-block">
                Github <i class="fa fa-github"></i>
            </a>
                        </div>
                    </div>
                </fieldset>
            </form>
            <div class="border-top py-1">
                <small class="text-muted">
                    Don't have an account? <a href="{% url 'signup' %}" class="ml-2">Sign Up</a>
                </small>
            </div>
        </div>
    </div>
</div>

<style>
    legend {
        color: #6912A7;
    }

    
    button {
        display: inline-block;
        font-weight: 400;
        color: snow;
        text-align: center;
        vertical-align: middle;
        cursor: pointer;
        user-select: none;
        background-color: #3ac57f;
        border: 1px solid transparent;
        padding: .375rem .75rem;
        font-size: 1rem;
        line-height: 1.5;
        border-radius: .25rem;
    }
    button:hover {
        background: #2ea569;
    }

    #id_username, #id_password{
        width: 100%;
        border: none;
        border-bottom: 3px #6912A7 solid;
        height: 20px;
        margin: -20px 0;
        outline: none;
        margin: 10px 0;
    }
    label {
        color: #666666;
        font-family: 'Nunito';
        font-weight: 600;
        margin:-10px 0;
    }
    #id_username:focus, #id_password:focus{
        border-bottom: 3px #3ac57f solid;
        transition: .5s;
    }

    .errorlist {
        list-style: none;
        margin: 0;
        padding: 0;
        font-weight: 600;
        color: crimson;
        font-family: 'Nunito' sans-serif;
    }
</style>
{% endblock content %}

templates/accounts/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Sign Up {% endblock title %}

{% block content %}

{% include 'partials/_message.html' %}

<div class="container mt-3">
    <h3 class="display-4"> You have been logged out. </h3>
<div class="border-top pt-3">
<small class="text-muted">
    Login again <a href="{% url 'login' %}" class="ml-2">Login</a>
</small>
</div>

</div>

<style>
    h3{
        color: #6912A7;
        font-family: 'Nunito' sans-serif;
    }
    button {
        display: inline-block;
        font-weight: 400;
        color: snow;
        text-align: center;
        vertical-align: middle;
        cursor: pointer;
        user-select: none;
        background-color: #2ea569;
        border: 1px solid transparent;
        padding: .375rem .75rem;
        font-size: 1rem;
        line-height: 1.5;
        border-radius: .25rem;
    }
</style>
{% endblock content %}

templates/accounts/password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Sign Up {% endblock title %}

{% block content %}

{% include 'partials/_message.html' %}

<div class="container py-2 mt-2 mb-3">
    <div class="row">
        <div class="col-md-6 mx-auto card">
            <form action="" method="POST" enctype="multipart/form-data" class="">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Change Password</legend>
                    {{ form }}
                </fieldset>
                <div class="form-group">
                    <button class="" type="submit">Save Changes</button>
                </div>
            </form>
            
        </div>
    </div>
</div>

<style>
    legend {
        color: #6912A7;
    }

    
    button {
        display: inline-block;
        font-weight: 400;
        color: snow;
        text-align: center;
        vertical-align: middle;
        cursor: pointer;
        user-select: none;
        background-color: #3ac57f;
        border: 1px solid transparent;
        padding: .375rem .75rem;
        font-size: 1rem;
        line-height: 1.5;
        border-radius: .25rem;
    }
    button:hover {
        background: #2ea569;
    }

    #id_new_password1, #id_new_password2, #id_old_password{
        width: 100%;
        border: none;
        border-bottom: 3px #6912A7 solid;
        height: 20px;
        margin: -20px 0;
        outline: none;
        margin: 10px 0;
    }
    label {
        color: #666666;
        font-family: 'Nunito';
        font-weight: 600;
        margin:-10px 0;
    }
    #id_username:focus, #id_password:focus{
        border-bottom: 3px #3ac57f solid;
        transition: .5s;
    }

    .errorlist {
        list-style: none;
        margin: 0;
        padding: 0;
        font-weight: 600;
        color: crimson;
        font-family: 'Nunito' sans-serif;
    }
</style>
{% endblock content %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} {% endblock title %}

{% block content %}

{% include 'partials/_message.html' %}
<div class="container py-2 mt-2">
    <div class="row">
        <div class="col-md-6 card mx-auto">
            <div class="row mt-2 py-2">
            <div class="col-md-4 col-sm-12"> 
                <img src="{{user.profile.avatar.url}}" alt="" class="user-avatar">  
            </div>

            <div class="col-md-6 col-sm-12">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{u_form}}
                
                    {{p_form}}
                    <small class="text-center">  </small>
                <input type="submit" value="Update">
                </form>
                <hr>
            <a href="{% url 'change-password' %}" id="pw-change" class="p-0 m-0"> Change Password </a>
            </div>
            </div>
        </div>
    </div>
</div>


<style>
    button {
        display: inline-block;
        font-weight: 400;
        color: snow;
        text-align: center;
        vertical-align: middle;
        cursor: pointer;
        user-select: none;
        background-color: #6912A7;
        border: 1px solid transparent;
        padding: .375rem .75rem;
        font-size: 1rem;
        line-height: 1.5;
        border-radius: .25rem;
    }
    .user-avatar {
        height: 100px;
        width: 100px;
        border-radius: 50%;
    }

    #id_username, #id_email{
        width: 100%;
        border: none;
        border-bottom: 3px #6912A7 solid;
        height: 20px;
        margin: -20px 0;
        outline: none;
        margin: 10px 0;
        font-weight: 600;
        font-size: 1em;
    }
    
    label {
        color: #666666;
        font-family: 'Nunito';
        font-weight: 600;
        margin:-10px 0;
    }
    #id_username:focus, #id_email:focus{
        border-bottom: 3px #3ac57f solid;
        transition: .5s;
    }
    input[type="file"] {
        display: none;
    }
    label[for="id_avatar"] {
        border: 2px solid #6912A7;
        display:block;
        margin: 5px 0;
        height:30px;
        padding: 3px 0;
        width: 60px;
        cursor: pointer;
    }
    label[for="id_avatar"]:hover {
        border: 2px solid #3ac57f;
        background: #3ac57f;
        color: white;
        transition: .3s;
    }
    small{
        display: none;
    }
    .show {
        display: block;
        color: #6912A7;
        font-weight: 600;
    }
    
    input[type="submit"] {
        border: 2px solid #3ac57f;
        display:block;
        margin: 5px 0;
        height:30px;
        padding: 3px 0;
        width: 100%;
        font-weight: 600;
        cursor: pointer;
        background: #3ac57f;
        color: white;
        text-align: center;
    }
    input[type="submit"]:hover {
        border: 2px solid #32a76c;
        background: #32a76c;
        color: white;
        transition: .3s;
    }
    #pw-change {
        text-decoration: none;
        color: #6912A7;
        font-size: 1rem;
        font-weight: 600;
        cursor: pointer;
    }
    #pw-change:hover {
        color: #32a76c;
        transition: .2s;
    }
</style>

<script>
    document.querySelector('#id_avatar').onchange = function () {
        var text = document.querySelector('small');
        text.innerHTML = 'selected image: ' + this.value;
        text.classList.add('show');
        };
</script>

{% endblock content %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Sign Up {% endblock title %}

{% block content %}

<div class="container py-2 mt-2 mb-3">
<div class="row">
    <div class="col-md-6 mx-auto card">
            <form action="" method="POST" enctype="multipart/form-data" class="">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Signup to Futbook </legend>
                    {{ form }}
                </fieldset>
                <div class="form-group">
                    <button class="" type="submit">Sign Up</button>
                </div>
            </form>   
            <div class="border-top py-1">
                    <small class="text-muted">
                        Already have an account? <a href="{% url 'login' %}" class="ml-2">Sign In</a>
                    </small>
                    </div>         
    </div>
</div>
</div>

<style>
    .card {
        width: 50rem;
    }
    legend{
        color: #6912A7;
    }
    button {
        display: inline-block;
        font-weight: 400;
        color: snow;
        text-align: center;
        vertical-align: middle;
        cursor: pointer;
        user-select: none;
        background-color: #3ac57f;
        border: 1px solid transparent;
        padding: .375rem .75rem;
        font-size: 1rem;
        line-height: 1.5;
        border-radius: .25rem;
    }
    button:hover {
        background: #2ea569;
    }

    #id_username, #id_email, #id_password1, #id_password2 {
        width: 100%;
        border: none;
        border-bottom: 3px #6912A7 solid;
        height: 20px;
        margin: -20px 0;
        outline: none;
        margin: 10px 0;
    }
    label {
        color: #666666;
        font-family: 'Nunito';
        font-weight: 600;
        margin:-10px 0;
    }
    #id_username:focus, #id_email:focus, #id_password1:focus, #id_password2:focus{
        border-bottom: 3px #3ac57f solid;
        transition: .5s;
    }
</style>


{% endblock content %}