futsal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',RedirectView.as_view(url='futsal/')),
    path('accounts/', include('accounts.urls')),
    path('futsal/',include('futsalApp.urls')),
    path('booking/',include('booking.urls')),
    path('team/',include('team.urls')),
    path('match/',include('match.urls')),
    ############# API ENDPOINTS #############
    path('api/auth/',include('accounts.api.urls')),
    path('api/booking/',include('booking.api.urls')),
    path('api/futsal/',include('futsalApp.api.urls')),
    path('api/team/',include('team.api.urls')),
    path('api/match/',include('match.api.urls')),
    ############ Social Authentication #########    
    path('oauth/',include('social_django.urls',namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

match/api/urls.py
from django.urls import path
from .views import MatchListAPI, MatchDetailAPI, MatchObjectListAPI, MatchObjectDetailAPI

urlpatterns = [
    path('',MatchListAPI.as_view(),name='match'),
    path('<int:pk>/',MatchDetailAPI.as_view(),name='match-detail'),
    path('match/',MatchObjectListAPI.as_view(),name='matchobj-list'),
    path('match/<int:pk>/',MatchObjectDetailAPI.as_view(),name='matchobj-detail'),
]

match/urls.py
from django.urls import path
from .views import (
    CreateMatchView,
    MatchIndexView,
    MatchFixView,
    MatchSearchView
)

urlpatterns = [
    path('',MatchIndexView.as_view(),name='match-index'),
    path('create/',CreateMatchView.as_view(),name='match-create'),
    path('fix',MatchFixView.as_view(),name='match-fix'),
    path('search',MatchSearchView.as_view(),name='match-search'),
]

team/urls.py
from django.urls import path
from .views import (TeamCreateView,
TeamDetailView,
TeamUpdateView,
JoinTeamView,
LeaveTeamView,
TeamDeleteView,
RemoveMemberView,
TeamIndexView,
TeamSearchView)

urlpatterns = [
    path('',TeamIndexView.as_view(),name='team-index'),
    path('create/',TeamCreateView.as_view(),name='team-create'),
    path('search',TeamSearchView.as_view(),name='team-search'),
    path('<slug:slug>',TeamDetailView.as_view(),name='team-detail'),
    path('update/<slug:slug>',TeamUpdateView.as_view(),name='team-update'),
    path('delete/<int:pk>/<slug:slug>',TeamDeleteView.as_view(),name='team-delete'),
    path('join/<slug:slug>/',JoinTeamView.as_view(),name='join-team'),
    path('leave/<slug:slug>/',LeaveTeamView.as_view(),name='leave-team'),
    path('remove/<slug:slug>/',RemoveMemberView.as_view(),name='remove-member'),
]

match/models.py
from django.db import models
from django.contrib.auth.models import User
from futsalApp.models import Futsal
from team.models import Team
# Create your models here.
class Match(models.Model):
    futsal       = models.ForeignKey(Futsal, on_delete=models.CASCADE)
    team         = models.ForeignKey(Team, on_delete=models.CASCADE)
    date         = models.DateField()
    start_time   = models.TimeField()
    end_time     = models.TimeField()
    player_count = models.IntegerField(default=5)
    timestamp    = models.DateTimeField(auto_now_add=True)
    game_type    = models.CharField(max_length=100, choices=(
        ('f', 'Friendly'),
        ('l', 'Loser\'s Pay')
    ))

    def __str__(self):
        return "Match of {}".format(self.team.name)

class MatchObject(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    opponent = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return 'Match between {} and {}'.format(self.match.team,self.opponent)

match/forms.py
from django import forms
from .models import Match

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class MatchForm(forms.ModelForm):
    date = forms.DateTimeField(widget=DateInput)
    start_time = forms.TimeField(widget=TimeInput,help_text='user hour-minute- AM/PM')
    end_time = forms.TimeField(widget=TimeInput,help_text='user hour-minute- AM/PM')
    class Meta:
        model = Match
        fields = [
            'team',
            'futsal',
            'date',
            'start_time',
            'end_time',
            'player_count',
            'game_type'
        ]
        exclude = ('team',)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control my-1'
    

match/api/views.py
from .serializers import MatchSerializer, MatchObjectSerializer
from rest_framework import generics, mixins
from match.models import Match, MatchObject


class MatchListAPI(generics.ListAPIView, mixins.CreateModelMixin):
    serializer_class = MatchSerializer

    def get_queryset(self):
        qs = Match.objects.all()
        return qs
    
    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)
    
class MatchDetailAPI(generics.RetrieveAPIView, mixins.UpdateModelMixin, mixins.DestroyModelMixin):
    serializer_class = MatchSerializer
    queryset         = Match.objects.all()

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)
    
    def patch(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)
    
    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class MatchObjectListAPI(generics.ListAPIView, mixins.CreateModelMixin):
    serializer_class = MatchObjectSerializer

    def get_queryset(self):
        qs = MatchObject.objects.all()
        return qs
    
    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

class MatchObjectDetailAPI(generics.RetrieveAPIView, mixins.UpdateModelMixin, mixins.DestroyModelMixin):
    serializer_class = MatchObjectSerializer
    queryset  = MatchObject.objects.all()

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)
    
    def patch(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)
    
    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

match/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponseRedirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from team.models import Team, TeamMember
from booking.models import Booking
from .models import Match, MatchObject
from .forms import MatchForm
import datetime
from django.db.models import Q

class MatchIndexView(LoginRequiredMixin, generic.ListView):
    model = Match
    template_name = 'match/index.html'

    def get_queryset(self):
        # this returns only the match requests who has no match objects
        match_requests = Match.objects.filter(matchobject__opponent=None)
        print(match_requests)
        return match_requests

    def check_team(self):
        try:
            has_team = TeamMember.objects.filter(user=self.request.user).exists()
        except:
            has_team = False
        return has_team

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['match_requests'] = self.get_queryset()
        context['has_team'] = self.check_team()
        return context

class CreateMatchView(LoginRequiredMixin, generic.CreateView):
    model = Match
    template_name = 'match/create.html'
    form_class = MatchForm

    def get_team(self):
        try:
            team = TeamMember.objects.get(user=self.request.user).team
            return team
        except:
            team = None
        return team

    def check_booking(self, obj):
        booking = Booking.objects.filter(futsal=obj.futsal,date=obj.date,time=obj.start_time).exists()
        return booking
    
    def check_match(self, obj):
        match = Match.objects.filter(futsal=obj.futsal,date=obj.date,start_time=obj.start_time).exists()
        return match

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.team = self.get_team()
        check_booking = self.check_booking(obj=instance)
        check_match   = self.check_match(obj=instance)
        while check_booking or check_match:
            instance = form.save(commit=False)
            messages.error(self.request,'Already booked for {} {}\n Try Again'.format(
                instance.date, instance.start_time))
            return redirect('match-create')
        # if there is no other bookings save !
        instance.save()
        messages.success(self.request, 'Match Request Sent.')
        return HttpResponseRedirect(instance.team.get_absolute_url())


class MatchFixView(LoginRequiredMixin, generic.RedirectView):
    
    def get_team(self): # users team 
        try:
            team = TeamMember.objects.get(user=self.request.user)
        except:
            team = None
        return team

    def get_redirect_url(self, *args, **kwargs):
        _team = self.get_team()
        team  = _team.team # users team 
        return reverse('team-detail', kwargs={'slug':team.slug})

    def post(self, request, *args, **kwargs):
        match_id = self.request.POST.get('match_id')
        team     = self.get_team() # users team 
        o_team   = self.request.POST.get('team_id') # opponent team
        print(o_team)
        try:
            match = Match.objects.get(id=match_id) # current match id to be post
            # new match object (team = team from list + opponent = users team )
            fix_match = MatchObject.objects.create(match=match, opponent=team.team)
            fix_match.save()
            messages.success(self.request, 'Game Fixed Successfully')
        except Exception as e:
            print(e)
            messages.warning(self.request, 'An error occoured')
        return super().get(request, *args, **kwargs)



class MatchSearchView(LoginRequiredMixin, generic.ListView):
    model = Team
    template_name = 'match/search.html'
    context_object_name = 'matches'

    def get_queryset(self):
        search_query = []
        request = self.request
        if request.GET.get('search_query'):
            search_term = request.GET['search_query']
            search_query = Match.objects.filter(
                Q(team__name__icontains = search_term) |
                Q(futsal__name__icontains = search_query)
            )
        
        if request.GET.get('game_type'):
            game = request.GET['game_type'] 
            search_query = Match.objects.filter(
                Q(game_type = game)
            )
        return search_query
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['match_requests'] = self.get_queryset()
        return context

templates/partials/match/fix_match.html
<div class="card my-2 p-1" id="item">
        <div class="team">
        <div class="img">
                <img class="" src="{{match.match.team.logo.url}}" alt="Card image cap" height="60" width="60" style="border-radius:50%" class="">
            </div>
            &nbsp;&nbsp;
            <div class="name">
            <span class="text-center" id="teamname"> 
                <a href="{{match.match.team.get_absolute_url}} "> {{match.match.team.name}}  </a>
            </span>
        </div>
        </div>
            <div class="details"> 
            <h4> VS </h4>
<small class="text-center"> {{match.match.date}} {{match.match.start_time}} </small>
<small class="text-center"> {{match.match.get_game_type_display}} </small>
<small class="text-center"> 
<a href="{{match.match.futsal.get_absolute_url}}"> 
    {{match.match.futsal.name}}
</a> </small>
            </div>
            <div class="team">
            <span class="text-center" id="teamname"> 
                    <a href="{{match.opponent.get_absolute_url}} "> {{match.opponent.name}}  </a>
                </span>
                &nbsp;&nbsp;
            <div class="img">
                <img class="" src="{{match.opponent.logo.url}}" alt="Card image cap" height="60" width="60" style="border-radius:50%">
            </div>
            </div>
</div>

<style>
    .team {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
    }
    .details {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    #item {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-evenly;
    }
    #teamname a {
        background: none;
        border: none;
        color: #7C33AA;
        font-size: 1.1rem;
    }
</style>

templates/partials/match/match_request.html
{% load static %}
<div class="card my-2 p-1" id="item">
        <div class="name">
                <span class="text-center" id="teamname"> 
                    <a href="{{match.team.get_absolute_url}} "> {{match.team.name}}  </a>
                </span>
            </div>
        <div class="team">
        <div class="img">
                <img class="" src="{{match.team.logo.url}}" alt="Card image cap" height="60" width="60" style="border-radius:50%" class="">
            </div>
            &nbsp;&nbsp;
        </div>
            <div class="details"> 
            <h5> VS </h5>
            <small>{{match.date}} <br> </small>
            <small> {{match.start_time}} <br> </small>
            <small> {{match.get_game_type_display}} </small>
            <small> <a href="{{match.futsal.get_absolute_url}}"> {{match.futsal.name}} </a> </small>
<small class="text-center"> {{match.match.date}} {{match.match.start_time}} </small>

            </div>
            <div class="team">
            <div class="img">
                    <img class="" src="{% static 'images/no.png' %}" alt="Card image cap" height="60" width="60" style="border-radius:50%" class="">
                </div>
                &nbsp;&nbsp;
                <div>
                {% if has_team %}
                <form action="{% url 'match-fix' %}" method="post">
                    {% csrf_token %}
                <input type="hidden" name="team_id" value="{{match.team.pk}}">
                <input type="hidden" name="match_id" value="{{match.pk}}">
                <button id="visit">Play</button>
                </form>
                {% endif %}
                </div>
            </div>
</div>

<style>
    .team {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
    }
    .details {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-items: center;
    }
    #item {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-evenly;
    }
    #teamname a {
        background: none;
        border: none;
        color: #7C33AA;
        font-size: 1.1rem;
    }
    small a {
        color: #33a56c;
    }
</style>