futsal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',RedirectView.as_view(url='futsal/')),
    path('accounts/', include('accounts.urls')),
    path('futsal/',include('futsalApp.urls')),
    path('booking/',include('booking.urls')),
    path('team/',include('team.urls')),
    path('match/',include('match.urls')),
    ############# API ENDPOINTS #############
    path('api/auth/',include('accounts.api.urls')),
    path('api/booking/',include('booking.api.urls')),
    path('api/futsal/',include('futsalApp.api.urls')),
    path('api/team/',include('team.api.urls')),
    path('api/match/',include('match.api.urls')),
    ############ Social Authentication #########    
    path('oauth/',include('social_django.urls',namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

futsalApp/api/urls.py
from django.urls import path
from .views import FutsalListAPI, FutsalDetailAPI
urlpatterns = [
    path('',FutsalListAPI.as_view(),name='futsal'),
    path('<int:pk>/',FutsalDetailAPI.as_view(),name='futsal-detail'),
]

futsalApp/urls.py
from django.urls import path
from .views import (HomePageView,
FutsalListView,
FutsalDetailView,
FutsalUpdateView,
FutsalSearchView
)
urlpatterns = [
    path('',HomePageView.as_view(),name='home'),
    path('list/',FutsalListView,name='futsal-list'),
    path('search',FutsalSearchView,name='futsal-search'),
    path('<slug:slug>/',FutsalDetailView,name='futsal-detail'),
    path('edit/<slug:slug>/',FutsalUpdateView.as_view(),name='futsal-edit'),
]

team/urls.py
from django.urls import path
from .views import (TeamCreateView,
TeamDetailView,
TeamUpdateView,
JoinTeamView,
LeaveTeamView,
TeamDeleteView,
RemoveMemberView,
TeamIndexView,
TeamSearchView)

urlpatterns = [
    path('',TeamIndexView.as_view(),name='team-index'),
    path('create/',TeamCreateView.as_view(),name='team-create'),
    path('search',TeamSearchView.as_view(),name='team-search'),
    path('<slug:slug>',TeamDetailView.as_view(),name='team-detail'),
    path('update/<slug:slug>',TeamUpdateView.as_view(),name='team-update'),
    path('delete/<int:pk>/<slug:slug>',TeamDeleteView.as_view(),name='team-delete'),
    path('join/<slug:slug>/',JoinTeamView.as_view(),name='join-team'),
    path('leave/<slug:slug>/',LeaveTeamView.as_view(),name='leave-team'),
    path('remove/<slug:slug>/',RemoveMemberView.as_view(),name='remove-member'),
]

booking/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from futsalApp.models import Futsal

class Booking(models.Model):
    fullname  = models.CharField(max_length=100)
    phone     = models.PositiveIntegerField()
    user      = models.ForeignKey(User, on_delete=models.CASCADE)
    futsal    = models.ForeignKey(Futsal, on_delete=models.CASCADE)
    time      = models.TimeField()
    date      = models.DateField()
    timestamp = models.DateTimeField(auto_now_add=True)
    updated   = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Booking of {} for {}'.format(self.user.username, self.futsal.name)
    
    def is_valid(self, *args, **kwargs):
        now = datetime.date.today()
        if now > self.date:
            return False
        return True
    
     

futsalApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from ckeditor.fields import RichTextField


# Create your models here.
class Futsal(models.Model):
    name        = models.CharField(max_length=200)
    location    = models.CharField(max_length=200)
    owner       = models.ForeignKey(User, on_delete=models.CASCADE)
    main_img    = models.ImageField(upload_to='Futsal')
    cover_img   = models.ImageField(upload_to='Cover')
    description = RichTextField()
    price       = models.PositiveIntegerField()
    slug        = models.SlugField(unique=True,blank=True,null=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    # location
    lat = models.FloatField(null=True, blank=True)
    lng = models.FloatField(null=True, blank=True)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('futsal-detail', kwargs={'slug':self.slug})
    
    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Futsal.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug,num)
            num += 1
        return unique_slug
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug(self)
        return super().save(*args, **kwargs)

match/models.py
from django.db import models
from django.contrib.auth.models import User
from futsalApp.models import Futsal
from team.models import Team
# Create your models here.
class Match(models.Model):
    futsal       = models.ForeignKey(Futsal, on_delete=models.CASCADE)
    team         = models.ForeignKey(Team, on_delete=models.CASCADE)
    date         = models.DateField()
    start_time   = models.TimeField()
    end_time     = models.TimeField()
    player_count = models.IntegerField(default=5)
    timestamp    = models.DateTimeField(auto_now_add=True)
    game_type    = models.CharField(max_length=100, choices=(
        ('f', 'Friendly'),
        ('l', 'Loser\'s Pay')
    ))

    def __str__(self):
        return "Match of {}".format(self.team.name)

class MatchObject(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    opponent = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return 'Match between {} and {}'.format(self.match.team,self.opponent)

booking/forms.py
from django import forms
from .models import Booking

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class BookingForm(forms.ModelForm):
    date = forms.DateTimeField(widget=DateInput)
    time = forms.TimeField(widget=TimeInput,help_text='user hour-minute- AM/PM')
    class Meta:
        model = Booking
        fields = [
            'fullname',
            'phone',
            'date',
            'time',
        ]

class CreateBookingForm(forms.ModelForm):
    date = forms.DateTimeField(widget=DateInput(attrs={'class':'form-control'}))
    time = forms.TimeField(widget=TimeInput, help_text='user hour-minute-AM/PM')
    class Meta:
        model = Booking
        fields = [
            'fullname',
            'phone',
            'futsal',
            'date',
            'time'
        ]

        widgets = {
            'fullname':forms.TextInput(attrs={'class':'form-control mb-2'}),
            'phone':forms.NumberInput(attrs={'class':'form-control mb-2'}),
            'futsal':forms.Select(attrs={'class':'form-control mb-2'}),
        }

futsalApp/forms.py
from django import forms
from .models import Futsal

class FutsalUpdateForm(forms.ModelForm):
    class Meta:
        model = Futsal
        fields = ['name', 'location', 'main_img', 'cover_img', 'description', 'price']

match/forms.py
from django import forms
from .models import Match

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class MatchForm(forms.ModelForm):
    date = forms.DateTimeField(widget=DateInput)
    start_time = forms.TimeField(widget=TimeInput,help_text='user hour-minute- AM/PM')
    end_time = forms.TimeField(widget=TimeInput,help_text='user hour-minute- AM/PM')
    class Meta:
        model = Match
        fields = [
            'team',
            'futsal',
            'date',
            'start_time',
            'end_time',
            'player_count',
            'game_type'
        ]
        exclude = ('team',)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control my-1'
    

futsalApp/api/views.py
from .serializers import FutsalSerializer
from rest_framework import generics, mixins, permissions, authentication
from futsalApp.models import Futsal
from django.db.models import Q

class FutsalListAPI(generics.ListAPIView):
    serializer_class = FutsalSerializer
    permission_classes = [permissions.AllowAny]
    
    def get_queryset(self):
        qs = Futsal.objects.all()
        query = self.request.GET.get('q')
        if query is not None:
            qs = qs.filter(
                Q(name__icontains=query) |
                Q(locaton__icontains=query)
            )
        return qs
    
class FutsalDetailAPI(generics.RetrieveAPIView):
    serializer_class = FutsalSerializer
    queryset    = Futsal.objects.all()
    permissions = [permissions.AllowAny]

futsalApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse,HttpResponseRedirect
from django.views import generic
from django.views.generic.edit import FormMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .paginator import proper_paginator
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from .models import Futsal
from .forms import FutsalUpdateForm
from accounts.models import Profile
from booking.models import Booking
from booking.forms import BookingForm, CreateBookingForm
import datetime
from django.db.models import Q
from team.models import Team, TeamMember

class HomePageView(LoginRequiredMixin,generic.ListView):
    model = Futsal
    template_name = 'futsalApp/index.html'
    queryset = Futsal.objects.all().order_by('?')[:3]
    context_object_name = 'futsals'

    def get_team(self):
        try:
            member = TeamMember.objects.get(user=self.request.user)
            return member.team.slug
        except:
            member = None
        return None

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['owner_futsals'] = Futsal.objects.filter(owner = self.request.user)
        context['team'] = self.get_team()
        return context
           
def FutsalListView(request):
    futsal_list = Futsal.objects.all().order_by('-id')
    paginator   = Paginator(futsal_list, 4)
    page        = request.GET.get('page')

    try:
        futsals = paginator.page(page)
    except PageNotAnInteger:
        futsals = paginator.page(1)
    except EmptyPage:
        futsals = paginator.page(paginator.num_pages)
    
    # To show limited number of paginators 
    if page is None:
        start_index = 0
        end_index   = 7
    else:
        (start_index, end_index) = proper_paginator(futsals, index=4)
    
    page_range = list(paginator.page_range)[start_index:end_index]

    context = {
        'futsals':futsals,
        'page_range':page_range,
    }
    return render(request, 'futsalApp/list.html', context)

    

class FutsalUpdateView(LoginRequiredMixin,SuccessMessageMixin,generic.UpdateView):
    model = Futsal
    form_class = FutsalUpdateForm
    success_message = 'Futsal Edited Successfully.'
    template_name = 'futsalApp/edit.html'

    def get_queryset(self):
        return Futsal.objects.filter(owner = self.request.user)
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        instance.slug  = instance._get_unique_slug()
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())

def FutsalSearchView(request):
    search_result = []
    if request.GET.get('futsal_name'):
        futsal = request.GET['futsal_name']
        search_result = Futsal.objects.filter(Q(name__icontains=futsal))
    
    if request.GET.get('futsal_location'):
        location = request.GET['futsal_location']
        search_result = Futsal.objects.filter(Q(location__icontains=location))
    
    if request.GET.get('futsal_price'):
        price = request.GET['futsal_price']
        search_result = Futsal.objects.filter(Q(price__lte=price))
    
    paginator = Paginator(search_result, 6)
    page      = request.GET.get('page')

    try:
        futsals = paginator.page(page)
    except PageNotAnInteger:
        futsals = paginator.page(1)
    except EmptyPage:
        futsals = paginator.page(paginator.num_pages)
        
    # To show limited number of paginators 
    if page is None:
        start_index = 0
        end_index   = 7
    else:
        (start_index, end_index) = proper_paginator(futsals, index=4)
    
    page_range = list(paginator.page_range)[start_index:end_index]

    context = {
        'futsals':futsals,
        'page_range':page_range,
    }

    return render(request, 'futsalApp/search.html', context)



def FutsalDetailView(request, slug):
    futsal = get_object_or_404(Futsal, slug=slug)
    user  = request.user
    # Booking form 
    if request.method == "POST":
        form = BookingForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = user 
            instance.futsal = futsal
            pre_booked = Booking.objects.filter(futsal=instance.futsal,date=instance.date,time=instance.time).exists()
            # check if futsal is pre booked 
            if pre_booked:
                messages.error(request,'Already booked by others.')
                instance = form.save(commit=False)
                return HttpResponseRedirect(futsal.get_absolute_url())

            instance.save()
            messages.success(request, 'Futsal Game Booked Successfully.')
            return HttpResponseRedirect(futsal.get_absolute_url())   
    else:
        print('error')
        form = BookingForm()
    # check if saved:
    is_saved = False
    if user.profile.favourites.filter(id=futsal.id).exists():
        is_saved = True
    else:
        is_saved = False
    
    # show bookings of the futsal for today
    bookings = Booking.objects.filter(
        futsal=futsal,
        date=datetime.date.today(),
        )

    context = {
        'form':form,
        'bookings':bookings,
        'futsal':futsal,
        'today':datetime.date.today(),
        'is_saved':is_saved,
        'lat':futsal.lat,
        'lng':futsal.lng,
    }
    return render(request, 'futsalApp/detail.html', context)
           
# def comment(request):
#     context = {}
#     if request.method == "POST":
#         form = ReviewForm(request.POST or None)
#         if form.is_valid():
#             instance = form.save(commit=False)
#             instance.futsal = request.POST.get('futsal_id')
#             print(instance.futsal)
#             instance.user = request.user
#             instance.save()
#             context['comment'] = instance.review
#             context['user']    = request.user.username
#             context['date']    = instance.date
#             context['futsal']  = instance.futsal
#             return JsonResponse({'data':context})
#     else:
#         form = ReviewForm()
#     return JsonResponse({'error':'Error occoured.'})


# class FutsalDetailView(LoginRequiredMixin, FormMixin, generic.DetailView):
#     model = Futsal
#     template_name = 'futsalApp/detail.html'
#     context_object_name = 'futsal'
#     slug_url_kwarg = 'slug'
#     form_class = BookingForm

#     def get_object(self, queryset=None):
#         obj = super().get_object(queryset=queryset)
#         return obj

#     def check_if_saved(self):
#         user = self.request.user
#         is_saved = False
#         if user.profile.favourites.filter(id=self.get_object().id).exists():
#             is_saved = True
#         return is_saved

#     def get_success_url(self):
#         return HttpResponseRedirect(reverse('futsal-detail', kwargs={'slug':self.get_object().slug}))
    
#     def get_context_data(self, **kwargs):
#         context = super(FutsalDetailView, self).get_context_data(**kwargs)
#         context['form'] = BookingForm(initial={'post':self.get_object()})
#         context['bookings'] = Booking.objects.filter(
#             futsal=self.get_object(),
#             date=datetime.date.today(),
#             )
#         context['today'] = datetime.date.today()
#         context['is_saved'] = self.check_if_saved()
#         context['review_form'] = ReviewForm()
#         # for frontend values
#         context['lat'] = self.get_object().lat
#         context['lng'] = self.get_object().lng
#         return context
    
#     def post(self, request, *args, **kwargs):
#         form = self.get_form()
#         if form.is_valid():
#             instance = form.save(commit=False)
#             instance.user = self.request.user
#             instance.futsal = self.get_object()
#             while Booking.objects.filter(futsal=instance.futsal,date=instance.date,time=instance.time).exists():
#                 messages.error(self.request,'Already booked')
#                 instance.save(commit=False)
#                 return HttpResponseRedirect(self.get_object().get_absolute_url())
#             instance.save()
#             messages.success(self.request, 'Futsal Game Booked Successfully.')
#             return self.get_success_url()
#         else:
#             messages.error(self.request, 'Booking Failed')
#             return HttpResponseRedirect(self.get_object().get_absolute_url())

templates/futsalApp/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{futsal.name}} {% endblock title %}

{% block content %}

{% include 'partials/_message.html' %}

<div class="container card mt-2 py-0 px-0 pb-2 mb-3">
    <div class="row m-0 p-0" id="cover"> 
      <img src="{{futsal.cover_img.url}}" alt="">  
    </div>

    <div class="futsal-detail">
        <div class="container-left">
            <div class="main-img">
                <img src="{{futsal.main_img.url}}" alt="" height="100" width="100">
            </div>
            <div class="info ml-md-2 ml-sm-0">
                <p> {{futsal.name}} </p>
                <p> <i class="fas fa-map-marker-alt"></i> {{futsal.location}} </p>
                <p> Rs. {{futsal.price}} </p>
            </div>
        </div>

        <div class="container-right">
    <button class="action-btn mt-2" id="book"><a href="" data-toggle="modal" data-target="#exampleModal">Book Now</a></button>

    <form action="{% url 'save' %}" method="post" id="saveForm">
        {% csrf_token %}
        <input type="hidden" name="futsal_id" value="{{futsal.pk}}">
    {% if is_saved %}
    <button class="action-btn mt-2" id="save" type="submit" style="background:#6912A7">Saved</button>
    {% else %}
    <button class="action-btn mt-2" id="save" type="submit">Save</button>
    {% endif %}
    </form>
    
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-md-7 col-sm-12 description">
            <div class="mx-1">
                {{futsal.description | safe }}
            </div>
        </div>

        <div class="col-md-5 col-sm-12 text-justify">
<h5 class="text-center" style="font-family:'Nunito';color:#7C33AA"> Booking for today 
    {{today}} </h5>
        <ul class="list-group mx-2">
            {% for booking in bookings %}
            {% if booking.user == request.user %}
            <li class="list-group-item disabled" aria-disabled="true" style="background:#5abd8b;color:white">
    Booked at {{booking.time}} <i class="fas fa-check-circle" style="color:white;"></i>
            </li>
                {% else %}
        <li class="list-group-item disabled" aria-disabled="true" >
             Booked at {{booking.time}} <i class="fas fa-check-circle" style="color: #33a56c;"></i>
        </li>
        {% endif %}
        {% endfor %}
        </ul>
        </div>
    </div>
    <hr>
    
    

    <div class="row">
        <div class="col">
        <div id="map" class="mx-1"></div> 
        </div>
    </div>

    
     <!-- Modal -->
     <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel" style="font-family:'Nunito';color:#6912A7">Book {{futsal.name}}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
        </div>
    <div class="modal-body">
    <form action="{% url 'futsal-detail' futsal.slug %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
    <!-- <button type="submit" class="">Book Futsal</button> -->
    <button type="submit">Book</button>
    </div>
    </form>
        </div>
    </div>
    </div>
    

</div>

<div class="hide">
    <p id="slug"> {{futsal.slug}} </p>
    <p id="lat"> {{futsal.lat}} </p>
    <p id="lng"> {{futsal.lng}} </p>
</div>

<style>
    body,html { overflow-x: hidden; }
    #cover img{
        height: 200px;
        width: 100%;
    }

    .futsal-detail {
        display: flex;
        width: 100%;
        margin: 10px;
        justify-content: space-between;
        align-items: center;
        height: 100px;
    }
    .main-img img {
        border-radius: 15px;
    }
    .container-left {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-around;
        height: 100%;
        width:  auto;
        
    }

    .container-left .info {
        margin-top: 10px;
        line-height: 10px;
        font-weight: 600;
        color: #7C33AA;
        font-size: 17px;
        font-family: 'Nunito';
    }

    .container-right {
        display: flex;
        justify-content: space-around;
        align-items: flex-start;
        height: 100%;
        width: 200px;
        padding-right:20px;
    }

    .action-btn {
        color: white;
        border: none;
        font-weight: 600;
        border-radius: 2px;
        cursor: pointer;
    }
    .action-btn a {
        font-weight: 600;
        font-family: 'Nunito';
        color: white;
        text-decoration: none;
    }
    #book {
        background: #7C33AA;
    }
    #book:hover{ background: rgb(77, 31, 105); transition: .2s; }

    #save {
        background: #33a56c;
    }
    #save:hover{ background: #277e52; transition: .2s; }

    .description { 
        text-align: justify; 
        border: none; 
        border-right: 2px solid rgb(155, 70, 207);
        font-size: 18px;
        font-family: 'Nunito';
        font-weight: 500;
    }
    .alert {
        font-family: 'Nunito' sans-serif;
        font-weight: 500;
    }

    button {
        display: inline-block;
        font-weight: 400;
        color: snow;
        text-align: center;
        vertical-align: middle;
        cursor: pointer;
        user-select: none;
        background-color: #3ac57f;
        border: 1px solid transparent;
        padding: .375rem .75rem;
        font-size: 1rem;
        line-height: 1.5;
        border-radius: .25rem;
    }
    button:hover {
        background: #2ea569;
    }

    label {
        color: #666666;
        font-family: 'Nunito';
        font-weight: 600;
        margin:5px 0;
    }
    #id_fullname, #id_phone, #id_futsal,#id_date, #id_time {
        font-size: 18px;
        font-weight: 500;
        font-family: 'Nunito';
    }
    #id_fullname:focus, #id_phone:focus, #id_price:focus,#id_description:focus {
        border-color: #3ac57f;
        transition: .2s;
    }
    #id_fullname, #id_phone, #id_futsal {
        width: 70%;
        border: none;
        border-bottom: 2px #6912A7 solid;
        height: 20px;
        margin: 20px;
        outline: none;
        margin: 10px 0;
    }
    #id_date,#id_time {
        width: 50%;
    }

    .hide {
        display: none;
    }
          
    .helptext {
        display: block;
        color: #6912A7;
        font-weight: 500;
        font-family: 'Nunito';
    }

    #map {
        height: 400px;
        width: 100%;
        margin: 0 auto;
    }

    @media screen and (max-width:698px) {
        .futsal-detail {
            justify-content: space-between;
            margin: 5px;
            height: auto;
            align-items: flex-start;
        }
        .main-img {
            display: none;
        }
        
        .container-left {
            flex: auto;
            width: auto;
            justify-content: start;
        }
        .container-left .info {
            font-size: 15px;
            line-height: 10px;
        }
        .container-right {
          
            width: auto;
            justify-content: space-around;
            flex-direction: column;
            align-items: flex-start;
        }
        .description {
            border: none;
        }
    }
</style>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDjyGjSln2wpTgzxdQdVtkKmGUXAud9jZA&callback=initMap&v=3"
async defer></script>

<script>

setInterval(function(){
    $("*").each(function() {
        if ($(this).css("zIndex") == 3) {
            $(this).css("zIndex", "-999");
        }
    })}
, 1);
var lat = $('#lat').text();
var lng = $('#lng').text();

function initMap() {
    // map options 
    var options = {
        zoom:17,
    }
    // new map 
    var map = new google.maps.Map(document.querySelector("#map"),options);

    let location1 = new google.maps.LatLng(lat,lng);

    // add map marker
    var marker = new google.maps.Marker({
        position:location1,
        map:map
    }); 
    marker.setVisible(true);

    
    // for info window 
    var infoWindow = new google.maps.InfoWindow({
        content:"<h3> This is boston </h3>",
    });

    // add event to the marker to display the info windoow 
    marker.addListener('click', function(){
        infoWindow.open(map, marker);
    });       
    var latLng = marker.getPosition(); 
    map.setCenter(latLng);
}


</script>

{% endblock content %}

templates/futsalApp/edit.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}

{% block content %}


<div class="container">
    {% if request.user == form.instance.owner %}
    <div class="row mt-2 py-3">
        <div class="col-md-7 mx-auto">
        <h3 class="text-left">  </h3>
            <div class="card p-2">
                <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form}}
                <button type="submit"> Save Changes </button>
                </form>
            </div>
        </div>
    </div>
    {% else %}

    <h3 class="text-bold text-center" style="font-family:'Nunito';color:#6912A7">
        Restricted!
    </h3>
    {% endif %}
</div>

<style>
        button {
            display: inline-block;
            font-weight: 400;
            color: snow;
            text-align: center;
            vertical-align: middle;
            cursor: pointer;
            user-select: none;
            background-color: #3ac57f;
            border: 1px solid transparent;
            padding: .375rem .75rem;
            font-size: 1rem;
            line-height: 1.5;
            border-radius: .25rem;
        }
        button:hover {
            background: #2ea569;
        }

        label {
            color: #666666;
            font-family: 'Nunito';
            font-weight: 600;
            margin:5px 0;
        }
        #id_name, #id_location, #id_price,#id_description {
            font-size: 18px;
            font-weight: 500;
            font-family: 'Nunito';
        }
        #id_name:focus, #id_location:focus, #id_price:focus,#id_description:focus {
            border-color: #3ac57f;
            transition: .2s;
        }
        #id_name, #id_location, #id_price  {
            width: 100%;
            border: none;
            border-bottom: 2px #6912A7 solid;
            height: 20px;
            margin: 20px;
            outline: none;
            margin: 10px 0;
        }
        #id_description {
            margin: 10px 0;
            width: 100%;
            height: 300px;
            border: 2.5px solid #666666;
        }
        input[type="file"] {
            display: none;
        }
        label[for="id_main_img"] {
            border: 2px solid #6912A7;
            display:block;
            margin: 5px 0;
            height:30px;
            padding: 3px 0;
            width: 80px;
            cursor: pointer;
        }
        label[for="id_cover_img"] {
            border: 2px solid #6912A7;
            display:block;
            margin: 5px 0;
            height:30px;
            padding: 3px 0;
            width: 100px;
            cursor: pointer;
        }
        label[for="id_main_img"]:hover,  label[for="id_cover_img"]:hover{
            border: 2px solid #3ac57f;
            background: #3ac57f;
            color: white;
            transition: .3s;
        }
</style>

{% endblock content %}

templates/futsalApp/search.html
{% extends 'base.html' %}

{% block title %} Futsal List {% endblock title %}

{% block content %}

<div class="container mt-2">
    <h4 class="text-left" style="color: #2f9c66;"> Search Results: </h4>
            <div class="row">
                {% for futsal in futsals %}
                {% include 'partials/_futsal_search_list.html' %}
                {% endfor %}
            </div>    
    </div>

    <hr>
    <!-- pagination here -->
<div class="container mt-2">
        {% if futsals %}
        <ul class="pagination">
            {% if futsals.has_previous %}
            <li class="page-item">
            <a href="?page{{futsal.previous_page_number}}" class="page-link">&laquo;</a>
            </li>
            {% endif %}
        <!-- looping the pagination -->
        {% for p in page_range %}
            {% if futsals.number == p %}

            <li class="page-item">
  <a href="?page={{p}}" class="page-link" style="background:rgb(47, 153, 100);color:seashell;" >{{p}}</a>
            </li>

            {% else %}

                <li class="page-item">
            <a href="?page={{p}}" class="page-link" >{{p}}</a>
            </li>

            {% endif %}

        {% endfor %}
    
        {# pagination to go to next page #}
        {% if homes.has_next %}
        <li class="page-item"> <a href="?page={{ homes.next_page_number }}" class="page-link"> &raquo; </a> </li>
        {% endif %}

    </ul>
        {% endif %}
    </div> 

<style>
#search-btn {
    background: #3ac57f;
    color: white;
    font-family: 'Nunito' sans-serif;
    font-weight: 600;
}
#search-btn:hover {
    background: #2f9c66;
    transition: .2s;
}
.input-group-text {
    background: #3ac57f;
    color: white;
}
</style>

{% endblock content %}